### PR TITLE
Adding new devices (AVR DA/DB, ATmega324PB)

### PR DESCRIPTION
**Pull request by doom-fr**
- integrate changes of svn #10000 patch (which adds AVR DA/DB devices)
- add ATmega324PB
- improve documentation
- remove tailing spaces in avrdude.conf

### CODE REVIEW

**Comment by facchinm** [comment]
Hi @doom-fr , thanks for the contribution! I just started the CI to produce the final binaries; will let you know when they are avaiable for broader testing.

**Comment by doom-fr** [comment]
Hi @facchinm , you're welcome and thanks for the merge !

**Comment by facchinm** [comment]
Compiled packages are available via usual package_index as `arduino:avrdude:6.3.0-arduino18`
@MCUdude

**Comment by MCUdude** [comment]
> Compiled packages are available via usual package_index as arduino:avrdude:6.3.0-arduino18

Are you referring to the development megaAVR boards manager URL? I deleted the Arduino15 folder on my computer when I tried to figure out what caused the >=64kiB bug in arduino-builder. Could you post the URL here, please?

EDIT: I found the development URL, but it can't be this. Any hints on where I can find the Avrdude-arduino18 version? 🙂

**Comment by per1234** [comment]
@MCUdude it's in the production package index, not the staging one:
https://downloads.arduino.cc/packages/package_index.json

Here's the definition for `arduino:avrdude:6.3.0-arduino18`:
```json
{
  "name": "avrdude",
  "version": "6.3.0-arduino18",
  "systems": [
    {
      "size": "220677",
      "checksum": "SHA-256:2e25c9e99c255d595a1072679a88ecddfa12c223b18510760bb867039f35efa5",
      "host": "arm-linux-gnueabihf",
      "archiveFileName": "avrdude-6.3.0-arduino18-armhf-pc-linux-gnu.tar.bz2",
      "url": "http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino18-armhf-pc-linux-gnu.tar.bz2"
    },
    {
      "size": "231047",
      "checksum": "SHA-256:4f88bb50d2235182ed7aa9e0a1d08e4bb956378ac9569b8e1141e37ed314fb2d",
      "host": "aarch64-linux-gnu",
      "archiveFileName": "avrdude-6.3.0-arduino18-aarch64-pc-linux-gnu.tar.bz2",
      "url": "http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino18-aarch64-pc-linux-gnu.tar.bz2"
    },
    {
      "size": "280072",
      "checksum": "SHA-256:df1dfd18e2e287c47232605cd4fa41751eb70df8c300aeb7a00a3a09b524a1b8",
      "host": "x86_64-apple-darwin12",
      "archiveFileName": "avrdude-6.3.0-arduino18-x86_64-apple-darwin12.tar.bz2",
      "url": "http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino18-x86_64-apple-darwin12.tar.bz2"
    },
    {
      "size": "254460",
      "checksum": "SHA-256:1ae46972b276b8a54c459f87c4ff326abdad0be2b1a293d73bf86e47765eddc3",
      "host": "x86_64-linux-gnu",
      "archiveFileName": "avrdude-6.3.0-arduino18-x86_64-pc-linux-gnu.tar.bz2",
      "url": "http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino18-x86_64-pc-linux-gnu.tar.bz2"
    },
    {
      "size": "329515",
      "checksum": "SHA-256:0781f4183e91a9783c2330035520144ab76b8f75c0a9f7a25877c063bc984c4d",
      "host": "i686-mingw32",
      "archiveFileName": "avrdude-6.3.0-arduino18-i686-w64-mingw32.zip",
      "url": "http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino18-i686-w64-mingw32.zip"
    }
  ]
}
```

**Comment by MCUdude** [comment]
@per1234 sorry, but I still can't figure it out. What do I do to make Arduino IDE install the Avrdude-arduino18 version? I added the json URL you linked to (just in case), removed the current megaAVR installation in the Arduino15 folder, but it still pulls arduino17 when I install the megaAVR 1.8.6 package.

**Comment by MCUdude** [comment]
OK, I think I get it. I manually downloaded the bz2 file and replaced avrdude-6.3.0-arduino17 with avrdude-6.3.0-arduino18 in the Arduino15 folder, and it worked. So I guess arduino18 will be downloaded automatically when the next megaavr (1.8.7) package is available.

**Comment by per1234** [comment]
>it still pulls arduino17

This is because that tool version is defined in the `toolsDependencies` field of the `arduino:megaavr@1.8.6` platform definition in the Boards Manager package index:
```json
{
  "name": "Arduino megaAVR Boards",
  "architecture": "megaavr",
  "version": "1.8.6",
  "category": "Arduino",
  "help": {
    "online": "http://www.arduino.cc/en/Reference/HomePage"
  },
  "url": "http://downloads.arduino.cc/cores/megaavr-1.8.6.tar.bz2",
  "archiveFileName": "megaavr-1.8.6.tar.bz2",
  "checksum": "SHA-256:d6d34aa9d7f2934c92c0a39cd8b48c6a1efb1820c59f558b5f8eddde63409eaa",
  "size": "856719",
  "boards": [
    {
      "name": "Arduino Uno WiFi Rev2"
    },
    {
      "name": "Arduino Nano Every"
    }
  ],
  "toolsDependencies": [
    {
      "packager": "arduino",
      "name": "avr-gcc",
      "version": "7.3.0-atmel3.6.1-arduino5"
    },
    {
      "packager": "arduino",
      "name": "avrdude",
      "version": "6.3.0-arduino17"
    },
    {
      "packager": "arduino",
      "name": "arduinoOTA",
      "version": "1.3.0"
    }
  ]
}
```
More information:
https://arduino.github.io/arduino-cli/latest/package_index_json-specification/#__code_3:~:text=toolsDependencies,-%3A%20the

>replaced avrdude-6.3.0-arduino17 with avrdude-6.3.0-arduino18 in the Arduino15 folder, and it worked

I'm glad to hear it! It's nice to have a shiny new version of AVRDUDE to play with.

> I guess arduino18 will be downloaded automatically when the next megaavr (1.8.7) package is available.

If they update the version specified in the `toolsDependencies` field, yes.

But if you want to use it in your cores, it's already available to you. You just need to make a release that specifies the `arduino:avrdude@6.3.0-arduino18` tool in `toolsDependencies` in your package index.

**Comment by MCUdude** [comment]
@facchinm Someone [opened an issue](https://github.com/MCUdude/MightyCore/issues/207) in one of my repos reporting that avrdude-6.3.0-arduino18 wasn't available for their Linux 32-bit system. Is it correct that the avrdude-6.3.0-arduino18 Linux 32-bit binary is actually missing?

**Comment by facchinm** [comment]
@MCUdude that's correct, I'm going to push 6.3.0-arduino19 with the linux32 platform in place :wink:

**Comment by MCUdude** [comment]
> MCUdude that's correct, I'm going to push 6.3.0-arduino19 with the linux32 platform in place 😉

Awesome! When will 6.3.0-arduino19 be available? And are there other changes between arduino18 and arduino19?

**Pull request merged**
